project:
  name: example
  description: A fast, minimalistic backend framework for Dart.
  version: 1.0.0

# modules:
#   - name: greeting
#     prefix: /greeting

env:
  default: development
# 
#   flavors:
#     development: .env
#     staging: .env.staging
#     production: .env.prod
