name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  get_it: ^8.0.3
  sarus:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus
      ref: main

dev_dependencies:
  build_runner: ^2.4.15
  sarus_gen:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus_gen
      ref: main
  test: ^1.24.0
  very_good_analysis: ^6.0.0
