name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sarus:
    path: ../packages/sarus
  stormberry:
    path: ../packages/stormberry

dev_dependencies:
  build_runner: ^2.4.15
  sarus_cli:
    path: ../packages/sarus_cli
  test: ^1.24.0
  very_good_analysis: ^6.0.0
