name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  sarus:
    path: ../packages/sarus
  shelf: ^1.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  sarus_cli:
    path: ../packages/sarus_cli
