name: my_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/sarus
  - packages/sarus_cli
  - packages/sarus_gen
  - packages/sarus_lint

dev_dependencies:
  melos: ^7.1.0

melos:

  sarus_cli:
    description: Install sarus_cli globally from local source
    command: |
      dart pub global deactivate sarus_cli
      dart pub global activate --source path ./packages/sarus_cli

  bricks:
    description: Install bricks globally from local source
    command: |
      mason bundle -s path ./bricks/project -o packages/sarus_cli/lib/templates/ -t dart
      mason bundle -s path ./bricks/module -o packages/sarus_cli/lib/templates/ -t dart
      dart format .
