name: sarus_cli
description: A fast, minimalistic backend framework for Dart.
version: 0.0.1-alpha.8
homepage: https://github.com/Prashant4900/sarus/
repository: https://github.com/Prashant4900/sarus/
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, shelf, sarus, cli]

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^7.4.5
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason: ^0.1.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0
  watcher: ^1.1.1
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  sarus:
