name: sarus_cli
description: The official command line interface for Sarus, built to streamline your development workflow.
version: 0.0.1-alpha.25
homepage: https://github.com/Prashant4900/sarus
repository: https://github.com/Prashant4900/sarus
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, shelf, sarus, cli]
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.1.1
  args: ^2.7.0
  cli_completion: ^0.5.1
  crypto: ^3.0.6
  http: ^1.5.0
  mason: ^0.1.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0
  watcher: ^1.1.3
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  build_runner: ^2.7.0
  build_verify: ^3.1.1
  build_version: ^2.1.2
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  sarus:
