name: hello_world
description: A fast, minimalistic backend framework for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sarus:
    path: ../../packages/sarus

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.24.0
  very_good_analysis: ^9.0.0
