name: {{name}}
description: A fast, minimalistic backend framework for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sarus:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus
      ref: development

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.24.0
  very_good_analysis: ^9.0.0
