name: {{name}}
description: A fast, minimalistic backend framework for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sarus:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus
      ref: development

dev_dependencies:
  build_runner: ^2.5.0
  lints: ^6.0.0
  sarus_gen:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus_gen
      ref: development
  sarus_lint:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus_lint
      ref: development
