name: {{name}}
description: A fast, minimalistic backend framework for Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  sarus: ^0.0.1-alpha.15

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  sarus_gen: ^0.0.1-alpha.2
  sarus_lint: ^0.0.1-alpha.2
