name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  sarus:
    path: ../../sarus/

dev_dependencies:
  sarus_gen:
    path: ../../sarus_gen/
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
