include: package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    avoid_print: ignore
    avoid_catches_without_on_clauses: ignore
    cascade_invocations: ignore
