include: package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    cascade_invocations: ignore
    empty_catches: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
