name: sarus
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_injector: ^2.1.0
  http_methods: ^1.1.1
  meta: ^1.16.0
  shelf: ^1.4.2
  stormberry:
    path: ../stormberry

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0