name: sarus
description: Sarus is a fast, minimalistic backend framework for Dart.
version: 0.0.1-alpha.11
homepage: https://github.com/Prashant4900/sarus/
repository: https://github.com/Prashant4900/sarus/
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, shelf, sarus, cli]

example:
  - example/lib/sarus_application.dart

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^7.4.5
  build: ^2.4.2
  collection: ^1.19.1
  dart_style: ^3.1.0
  equatable: ^2.0.7
  http_methods: ^1.1.1
  meta: ^1.17.0
  shelf: ^1.4.2
  source_gen: ^2.0.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0