name: sarus
description: Sarus is a fast, minimalistic backend framework for Dart.
version: 0.0.1-alpha.15
homepage: https://github.com/Prashant4900/sarus/
repository: https://github.com/Prashant4900/sarus/
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, shelf, sarus, cli]
resolution: workspace

example:
  - example/lib/sarus_application.dart

environment:
  sdk: ^3.9.0

dependencies:
  http_methods: ^1.1.1
  meta: ^1.17.0
  shelf: ^1.4.2

dev_dependencies:
  very_good_analysis: ^9.0.0