include: package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    avoid_catches_without_on_clauses: ignore
