builders:
  route_builder:
    import: "package:sarus_gen/builder.dart"
    builder_factories: ["routeBuilder"]
    build_extensions: {".dart": [".routes.g.part"]}  # Explicit part files
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]  # Re-enable combiner

  stormberry:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "analyzeSchema" ]
    build_extensions: { ".dart": ["___"] }
    auto_apply: dependents
    build_to: cache
    runs_before: [":schema", ":runner"]
  schema:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildSchema" ]
    build_extensions: { ".dart": [ ".schema.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: ["dart_mappable_builder", "freezed", "json_serializable"]
  runner:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildRunner" ]
    build_extensions: { ".dart": [ ".schema.json" ] }
    auto_apply: dependents
    build_to: cache

targets:
  $default:
    builders:
      stormberry:
        generate_for:
          - test/**/*.dart
      stormberry|schema:
        generate_for:
          - test/**/*.dart
      stormberry|runner:
        generate_for:
          - test/**/*.dart
      build_test:test_bootstrap:
        enabled: false