builders:
  sarus_application_builder:
    import: "package:sarus_gen/builder.dart"
    builder_factories: ["applicationBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    # runs_before: ["source_gen|combining_builder"]

  model_builder:
    import: "package:sarus_gen/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    # runs_before: ["source_gen|combining_builder"]

  endpoint_builder:
    import: "package:sarus_gen/builder.dart"
    builder_factories: ["endpointBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    # runs_before: ["source_gen|combining_builder"]
