builders:
  route_builder:
    import: "package:sarus_gen/builder.dart"
    builder_factories: ["routeBuilder"]
    build_extensions: {".dart": [".routes.g.part"]}  # Explicit part files
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]  # Re-enable combiner