name: sarus_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha.1
homepage: https://github.com/Prashant4900/sarus
repository: https://github.com/Prashant4900/sarus
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, generated, shelf, sarus]

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^7.5.5
  build: ^2.5.4
  dart_style: ^3.1.0
  glob: ^2.1.3
  sarus: 0.0.1-alpha.14
  source_gen: ^2.0.0

dev_dependencies:
  very_good_analysis: ^9.0.0
