name: sarus_gen
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  dart_style: ^3.0.1
  sarus:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus
      ref: main
  source_gen: ^2.0.0


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0