name: sarus_gen
description: Official code generator for Sarus backend framework.
version: 0.0.1-alpha.2
homepage: https://github.com/Prashant4900/sarus
repository: https://github.com/Prashant4900/sarus
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, generated, shelf, sarus]
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.1.1
  build: ^3.0.2
  dart_style: ^3.1.0
  glob: ^2.1.3
  path: ^1.9.1
  sarus: 0.0.1-alpha.15
  source_gen: ^4.0.0

dev_dependencies:
  very_good_analysis: ^9.0.0
