name: sarus_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^7.5.5
  build: ^2.5.4
  dart_style: ^3.1.0
  glob: ^2.1.3
  sarus:
    path: ../sarus/
  source_gen: ^2.0.0

dev_dependencies:
  very_good_analysis: ^9.0.0
