name: sarus_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Prashant4900/sarus
repository: https://github.com/Prashant4900/sarus
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, lints, shelf, sarus, cli]

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
