name: sarus_lint
description: Official lint rules for Sarus backend framework.
version: 0.0.1-alpha.2
homepage: https://github.com/Prashant4900/sarus
repository: https://github.com/Prashant4900/sarus
issue_tracker: https://github.com/Prashant4900/sarus/issues
topics: [server, backend, lints, shelf, sarus]
resolution: workspace

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
