version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sarus_db
      DB_USER: postgres
      DB_PASS: postgres
    networks:
      - sarus-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sarus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - sarus-db:/var/lib/postgresql/data
    networks:
      - sarus-network

volumes:
  sarus-db:

networks:
  sarus-network:
