name: src
description: A new jaspr project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.2.0
  dotenv: ^4.2.0
  jaspr: ^0.18.0
  path: ^1.9.1
  sarus:
    git:
      url: https://github.com/Prashant4900/sarus.git
      path: packages/sarus
  stormberry:
    git:
      url: https://github.com/Prashant4900/stormberry.git

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.2
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1
  lints: ^5.0.0

jaspr:
  mode: server
  dev-command: dart_frog dev
