import 'package:hello_world/greeting/endpoints.dart';
import 'package:hello_world/hello/endpoints.dart';
import 'package:hello_world/sarus_application.g.dart';
import 'package:sarus/sarus.dart';

final router = Router(
  globalMiddleware: [logRequests()],
  routes: $routes,
);

// // this will be generated by sarus in final build
// final List<Route> $routes = [
//   GreetingRoute(),
//   HelloRoute(),
// ];

// this will we new route definition
class GreetingRoute extends Route {
  GreetingRoute()
    : super(
        prefix: '/greeting',
        endpoints: [GreetingEndpoints()],
      );
}

class HelloRoute extends Route {
  HelloRoute()
    : super(
        endpoints: [HelloEndpoints()],
        middlewares: [logRequests()],
      );
}
